# Development Docker Compose Configuration
# Use this for local development with hot reload

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: one3tap_dev_db
      POSTGRES_USER: one3tap_dev_user
      POSTGRES_PASSWORD: one3tap_dev_password
    ports:
      - "5432:5432"
    networks:
      - one3tap_dev_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - one3tap_dev_network

  # Django Web Application (Development)
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount source code for hot reload
      - static_volume_dev:/app/staticfiles
      - media_volume_dev:/app/media
      - logs_volume_dev:/app/logs
    environment:
      DEBUG: "True"
      SECRET_KEY: "dev-secret-key-not-for-production"
      DATABASE_URL: "postgresql://one3tap_dev_user:one3tap_dev_password@db:5432/one3tap_dev_db"
      REDIS_URL: "redis://redis:6379/1"
      ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py migrate &&
             python manage.py create_templates &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - one3tap_dev_network

volumes:
  postgres_data_dev:
    driver: local
  static_volume_dev:
    driver: local
  media_volume_dev:
    driver: local
  logs_volume_dev:
    driver: local

networks:
  one3tap_dev_network:
    driver: bridge
