# Generated by Django 5.2.3 on 2025-07-27 04:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('shipping_address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('pvc_cards', models.IntegerField(default=0)),
                ('wood_cards', models.IntegerField(default=0)),
                ('metal_cards', models.IntegerField(default=0)),
                ('pvc_standees', models.IntegerField(default=0)),
                ('wood_standees', models.IntegerField(default=0)),
                ('metal_standees', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('manufacturing', 'Manufacturing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NFCCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registration_code', models.CharField(editable=False, max_length=16, unique=True)),
                ('card_type', models.CharField(choices=[('pvc', 'PVC Card'), ('wood', 'Wood Card'), ('metal', 'Metal Card')], max_length=10)),
                ('batch_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('manufactured', 'Manufactured'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('registered', 'Registered'), ('active', 'Active'), ('inactive', 'Inactive')], default='manufactured', max_length=15)),
                ('manufactured_date', models.DateTimeField(auto_now_add=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('order_reference', models.CharField(blank=True, max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_slug', models.SlugField(unique=True)),
                ('card_title', models.CharField(default='Digital Business Card', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('custom_links', models.JSONField(blank=True, default=dict)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='card_profiles/')),
                ('show_email', models.BooleanField(default=True)),
                ('show_phone', models.BooleanField(default=True)),
                ('show_social_links', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_cards', to=settings.AUTH_USER_MODEL)),
                ('nfc_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_card', to='main.nfccard')),
            ],
        ),
        migrations.CreateModel(
            name='CardAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('contact_downloaded', models.BooleanField(default=False)),
                ('links_clicked', models.JSONField(blank=True, default=list)),
                ('digital_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='main.digitalcard')),
            ],
        ),
    ]
