# Generated by Django 5.2.3 on 2025-08-04 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cardorder_nfccard_digitalcard_cardanalytics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NFCCard',
            new_name='VisitingCard',
        ),
        migrations.RenameField(
            model_name='digitalcard',
            old_name='nfc_card',
            new_name='visiting_card',
        ),
    ]
