# Generated by Django 5.2.3 on 2025-08-12 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_nfccard_to_visitingcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('corporate', 'Corporate'), ('creative', 'Creative'), ('minimal', 'Minimal'), ('modern', 'Modern'), ('premium', 'Premium'), ('startup', 'Startup'), ('tech', 'Technology'), ('medical', 'Medical'), ('legal', 'Legal'), ('consulting', 'Consulting'), ('custom', 'Custom')], default='corporate', max_length=20)),
                ('html_template', models.TextField(help_text='HTML template content')),
                ('css_content', models.TextField(help_text='CSS styling content')),
                ('js_content', models.TextField(blank=True, help_text='JavaScript functionality content')),
                ('primary_color', models.CharField(default='#0088FF', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#00D4FF', help_text='Hex color code', max_length=7)),
                ('font_family', models.CharField(default='Inter, sans-serif', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='template_thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('template_folder', models.CharField(blank=True, help_text='Folder path for template assets', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='company_template',
            field=models.ForeignKey(blank=True, help_text='Company-specific template for this card', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.companytemplate'),
        ),
    ]
